# Generated by Django 5.2.2 on 2025-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='preferred_location',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='hear_about_us',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='move_in_timeline',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1-3 months', '1–3 months'), ('6+ months', '6+ months')], max_length=50),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='team_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
